### ISSUE TITLE
Error in filetype plugin when loading .fsx file

### ISSUE THREAD

**Issue by benfranklin79** [fsharp/vim-fsharp#100]
When I edit a script file in vim I get the following

    Error detected while processing /Users/benfranklin/.vim/bundle/vim-fsharp/ftplugin/fsharp.vim:
    line   81:
    Traceback (most recent call last):
      File "<string>", line 25, in <module>
      File "<string>", line 21, in get_path
    TypeError: argument of type 'NoneType' is not iterable

**Comment by benfranklin79** [comment]
May have a workaround. I tried explicitly loading the plugin (I'm using https://github.com/junegunn/vim-plug) using the command

    :PlugInstall vim-fsharp

and then tried reloading the file (:e % when in the file) and I don't get the error and the syntax highlighting is back

**Comment by kjnilsson** [comment]
Something might be wrong with the plug config perhaps? I don’t use it
myself so PRs are greatly appreciated. :)
