### ISSUE TITLE
Error when opening fs-files (fsharpvim.py, get_paths)

### ISSUE THREAD

**Issue by b0wter** [fsharp/vim-fsharp#101]
I've installed this plugin using vim-plug on openSUSE Tumbleweed. I keep everything up-to-date (only distribution provided packages).
This is the error message I got initially:

**Error message:**
```
"Program.fs" [noeol] 96L, 3439C
Error detected while processing /home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharp.vim:
line   81:
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "<string>", line 22, in get_path
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 165, in get_paths
    return self._getpaths.send("compilerlocation\n")
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 47, in send
    self._write(command)
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 32, in _write
    self.proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "<string>", line 22, in get_path
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 165, in get_paths
    return self._getpaths.send("compilerlocation\n")
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 47, in send
    self._write(command)
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 32, in _write
    self.proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
"Program.fs" [noeol] 96L, 3439C
Error detected while processing /home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharp.vim:
line   81:
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "<string>", line 22, in get_path
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 165, in get_paths
    return self._getpaths.send("compilerlocation\n")
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 47, in send
    self._write(command)
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 32, in _write
    self.proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "<string>", line 22, in get_path
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 165, in get_paths
    return self._getpaths.send("compilerlocation\n")
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 47, in send
    self._write(command)
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 32, in _write
    self.proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```
So I rechecked the options and added the following to my vimrc:
```
let g:fsharp_interactive_bin = '/usr/bin/fsharpi'
let g:fsharp_xbuild_path = "/usr/bin/xbuild"
```
Which reduced the amount of errors, but didnt fix them:

```
Error detected while processing /home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharp.vim:
line   81:
Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 154, in parse
    self.send(line + "\n")
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 106, in send
    self.p.stdin.write(txt)
BrokenPipeError: [Errno 32] Broken pipe
Error detected while processing function fsharpbinding#python#OnBufEnter:
line   10:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 152, in parse
    self.send("parse \"%s\"\n" % (fn))
  File "/home/b0wter/.vim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 106, in send
    self.p.stdin.write(txt)
BrokenPipeError: [Errno 32] Broken pipe
```

**Mono version:**
```Mono JIT compiler version 5.4.1.7 (tarball Tue Jan 30 16:00:27 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

```

**VIM version:**
```
VIM - Vi IMproved 8.0 (2016 Sep 12)
Included patches: 1-1442
Compiled by 'http://www.opensuse.org/'
Huge version without GUI.
```

**Comment by kjnilsson** [comment]
I have never tested installation using plug. It looks like make was never
run. Can you try running make in the vim-fsharp directory manually?

**Comment by b0wter** [comment]
Completely my fault. The installation with vim-plug works just fine but you have to use the correct command:

```
Plug 'fsharp/vim-fsharp', {
      \ 'for': 'fsharp',
      \ 'do':  'make fsautocomplete',
      \}
```

I've just blindly copied the command given in the summary on vimawesome.com
