### ISSUE TITLE
Error after install when opening .fs file

### ISSUE THREAD

**Issue by jbpratt** [fsharp/vim-fsharp#108]
I may have missed a step during install through Vim-Plug, but I have tried twice now as well as ran the bash script. Any advice would be appreciated :smile: 
```
Error detected while processing /home/jbpratt/.vim/plugged/vim-fsharp/ftplugin/fsharp.vim:
line   81:
Traceback (most recent call last):
  File "/home/jbpratt/.vim/plugged/vim-fsharp/ftplugin/fsi.py", line 26, in __init__
    self.p = Popen(command, **opts)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'fsharpi': 'fsharpi'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 28, in <module>
  File "/home/jbpratt/.vim/plugged/vim-fsharp/ftplugin/fsi.py", line 28, in __init__
    raise Exception ('Error executing fsi.  g:fsharp_interactive_bin="' + fsi_path + '" ' + str(e))
Exception: Error executing fsi.  g:fsharp_interactive_bin="fsharpi" [Errno 2] No such file or directory: 'fsharpi': 'fsharpi'
```

**Comment by jbpratt** [comment]
Got it, running on Arch. Simply had to rebuild FSharp.
