### ISSUE TITLE
Triggering completion after System.Char. results in UnicodeEncodeError

### ISSUE THREAD

**Issue by kjnilsson** [fsharp/vim-fsharp#38]
Error detected while processing function fsharpbinding#python#Complete:
line   43:
Traceback (most recent call last):
Error detected while processing function fsharpbinding#python#Complete:
line   43:
  File "<string>", line 11, in <module>
Error detected while processing function fsharpbinding#python#Complete:
line   43:
  File "/Users/karlnilsson/code/kjnilsson/vim-fsharp/ftplugin/fsharpvim.py", line 213, in helptext
Error detected while processing function fsharpbinding#python#Complete:
line   43:
    output = output + str(ol['Signature']) + "\n"
Error detected while processing function fsharpbinding#python#Complete:
line   43:
UnicodeEncodeError: 'ascii' codec can't encode character u'\uffff' in position 23: ordinal not in range(128)

**Comment by kjnilsson** [comment]
fixed
