### ISSUE TITLE
python error message

### ISSUE THREAD

**Issue by dcmwong** [fsharp/vim-fsharp#41]
I'm on a mac running ubuntu 14.04 on a VM.

Installed vim-fsharp through vundle, opened a fsx file and I get this error:

Error detected while processing /home/vagrant/.vim/bundle/vim-fsharp/ftplugin/fsharp.vim:
line   65:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vagrant/.vim/bundle/vim-fsharp/ftplugin/fsharpvim.py", line 108, in work
    parsed = json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "<string>", line 22, in get_path
  File "/home/vagrant/.vim/bundle/vim-fsharp/ftplugin/fsharpvim.py", line 149, in get_paths
    return self._getpaths.send("compilerlocation\n")
  File "/home/vagrant/.vim/bundle/vim-fsharp/ftplugin/fsharpvim.py", line 43, in send
    self._write(command)
  File "/home/vagrant/.vim/bundle/vim-fsharp/ftplugin/fsharpvim.py", line 28, in _write
    self.proc.stdin.write(txt)
IOError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "<string>", line 22, in get_path
  File "/home/vagrant/.vim/bundle/vim-fsharp/ftplugin/fsharpvim.py", line 149, in get_paths
    return self._getpaths.send("compilerlocation\n")
  File "/home/vagrant/.vim/bundle/vim-fsharp/ftplugin/fsharpvim.py", line 43, in send
    self._write(command)
  File "/home/vagrant/.vim/bundle/vim-fsharp/ftplugin/fsharpvim.py", line 28, in _write
    self.proc.stdin.write(txt)
IOError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "<string>", line 22, in get_path
  File "/home/vagrant/.vim/bundle/vim-fsharp/ftplugin/fsharpvim.py", line 149, in get_paths
    return self._getpaths.send("compilerlocation\n")
  File "/home/vagrant/.vim/bundle/vim-fsharp/ftplugin/fsharpvim.py", line 43, in send
    self._write(command)
  File "/home/vagrant/.vim/bundle/vim-fsharp/ftplugin/fsharpvim.py", line 28, in _write
    self.proc.stdin.write(txt)
IOError: [Errno 32] Broken pipe

**Comment by kjnilsson** [comment]
I don't use vundle myself but I've heard similar reports before. could you
try to follow the pathogen install instructions (run make manually)?

**Comment by elliottt** [comment]
I had the same problem, and running `make` manually fixed it for me. Thanks!

**Comment by dcmwong** [comment]
Sorry for the late reply.  Yes running make manually fixed it.
