### ISSUE TITLE
[Neovim]

### ISSUE THREAD

**Issue by Banashek** [fsharp/vim-fsharp#66]
Neovim 0.1.7
Macos 10.11.6 (el capitan)

Error upon opening any F# file

Stack trace leads here: https://github.com/fsharp/vim-fsharp/blob/master/ftplugin/fsharp.vim#L65

```
"client/App.fs" [noeol] 59L, 1298C
Error detected while processing /Users/jonbanashek/.config/nvim/plugged/vim-fsharp/ftplugin/fsharp.vim:
line   65:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jonbanashek/.config/nvim/plugged/vim-fsharp/ftplugin/fsharpvim.py", line 114, in work
    parsed = json.loads(data)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(Thread-1, stopped daemon 123145306509312)>>
Traceback (most recent call last):
Error detected while processing function provider#python#Call:
line   18:
Channel 1 returned a response that doesn't have a matching request id. Ensure the client is properly synchronized
Invalid channel "1"
Invalid channel "1"
Invalid channel "1"
Error detected while processing function fsharpbinding#python#OnBufEnter[10]..provider#python#Call:
line   18:
Invalid channel "1"
```

**Comment by kjnilsson** [comment]
How did you you install it?

**Comment by Banashek** [comment]
Via plugged.

Here is my vimrc section for vim-fsharp

```
" FSharp
Plug 'fsharp/vim-fsharp', {
      \ 'for': 'fsharp',
      \ 'do':  'make fsautocomplete',
      \}
```

**Comment by kjnilsson** [comment]
Can you try running make manually?

**Comment by Banashek** [comment]
Yeah that worked perfectly

**Comment by Banashek** [comment]
Jeeze you respond fast. I really appreciate that!

**Comment by kjnilsson** [comment]
Ok. I don't use plug so if you know how the config could be made to work
feel free to issue a pr. cheers.

**Comment by Banashek** [comment]
Thanks I'll check it out!
