### ISSUE TITLE
.NET Core does not work. 

### ISSUE THREAD

**Issue by Tombert** [fsharp/vim-fsharp#98]
I recently installed .NET core on Ubuntu, and when I try opening an FS file, I get the following error: 

```
Error detected while processing function provider#python3#Call:                                                                                                          
line   18:                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                       
  File "/home/tombert/.local/share/nvim/plugged/vim-fsharp/ftplugin/fsi.py", line 26, in __init__                                                                        
    self.p = Popen(command, **opts)                                                                                                                                      
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__                                                                                                         
    restore_signals, start_new_session)                                                                                                                                  
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child                                                                                                  
    raise child_exception_type(errno_num, err_msg)                                                                                                                       
FileNotFoundError: [Errno 2] No such file or directory: 'fsharpi'                                                                                                        
During handling of the above exception, another exception occurred:                                                                                                      
Traceback (most recent call last):                                                                                                                                       
  File "<string>", line 28, in <module>                                                                                                                                  
  File "/home/tombert/.local/share/nvim/plugged/vim-fsharp/ftplugin/fsi.py", line 28, in __init__                                                                        
    raise Exception ('Error executing fsi.  g:fsharp_interactive_bin="' + fsi_path + '" ' + str(e))                                                                      
Exception: Error executing fsi.  g:fsharp_interactive_bin="fsharpi" [Errno 2] No such file or directory: 'fsharpi'                                                       
Traceback (most recent call last):                                                                                                                                       
  File "/home/tombert/.local/share/nvim/plugged/vim-fsharp/ftplugin/fsi.py", line 26, in __init__                                                                        
    self.p = Popen(command, **opts)                                                                                                                                      
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__                                                                                                         
    restore_signals, start_new_session)                                                                                                                                  
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child                                                                                                  
    raise child_exception_type(errno_num, err_msg)                         

```

Is there something additional that I have to do to make my project work?

**Comment by Tombert** [comment]
I should point out that the type info and whatnot *does* show up on VSCode, leading me to believe I might have configured something wrong with Vim

**Comment by kjnilsson** [comment]
Seems it is somehow it trying to run the fsi and you don't have it (`fsharpi`) available. You could try installing mono.

**Comment by Tombert** [comment]
@kjnilsson Does the plugin not work with .NET Core by itself?

**Comment by kjnilsson** [comment]
@Tombert no the completion and checking server (fsautocomplete) requires mono, for now.

**Comment by Tombert** [comment]
@kjnilsson Ah, ok; out of curiosity, what is missing to make it work correctly?  Is the issue that .NET Core doesn't have a REPL as of right now?

**Comment by kjnilsson** [comment]
Amongst other things. It is being worked on I believe.

**Comment by Tombert** [comment]
@kjnilsson Alright, thanks for clarifying.
